[workspace]
members = [
    "audio/ac97d",
    "interfaces/acpid",
    "storage/ahcid",
    "net/alxd",
    "virt/bgad",
    "storage/block-io-wrapper",
    "common",
    "net/e1000d",
    "storage/ided",
    "audio/ihdad",
    "net/ixgbed",
    "storage/nvmed",
    "other/lived", # TODO: not really a driver...
    "interfaces/pcid",
    "audio/pcspkrd",
    "input/ps2d",
    "net/rtl8139d",
    "net/rtl8168d",
    "audio/sb16d",
    "virt/vboxd",
    "video/vesad",
    "interfaces/xhcid",
    "usbctl",
    "input/usbhidd",
    "storage/usbscsid",
    "other/inputd",
    "virt/virtio-blkd",
    "virt/virtio-netd",
    "virt/virtio-gpud",
    "virt/virtio-core",
]

[profile.release]
lto = "fat"

[patch.crates-io]
mio = { git = "https://gitlab.redox-os.org/redox-os/mio.git", branch = "redox-unix" }
net2 = { git = "https://gitlab.redox-os.org/redox-os/net2-rs.git", branch = "master" }
orbclient = { git = "https://gitlab.redox-os.org/redox-os/orbclient.git", version = "0.3.44" }
