[workspace]
members = [
    "ac97d",
    "acpid",
    "ahcid",
    "alxd",
    "bgad",
    "block-io-wrapper",
    "common",
    "e1000d",
    "ided",
    "ihdad",
    "ixgbed",
    "nvmed",
    "lived", # TODO: not really a driver...
    "pcid",
    "pcspkrd",
    "ps2d",
    "rtl8139d",
    "rtl8168d",
    "sb16d",
    "vboxd",
    "vesad",
    "xhcid",
    "usbctl",
    "usbhidd",
    "usbscsid",
    "inputd",

    "virtio-blkd",
    "virtio-netd",
    "virtio-gpud",
    "virtio-core",
]

[profile.release]
lto = "fat"

[patch.crates-io]
mio = { git = "https://gitlab.redox-os.org/redox-os/mio.git", branch = "redox-unix" }
net2 = { git = "https://gitlab.redox-os.org/redox-os/net2-rs.git", branch = "master" }
orbclient = { git = "https://gitlab.redox-os.org/redox-os/orbclient.git", version = "0.3.44" }
redox_syscall = { git = "https://gitlab.redox-os.org/redox-os/syscall.git" }
