[workspace]
members = [
    "ahcid",
    "alxd",
    "bgad",
    "e1000d",
    "ihdad",
    "ixgbed",
    "nvmed",
    "pcid",
    "pcspkrd",
    "ps2d",
    "rtl8168d",
    "vboxd",
    "vesad",
    "xhcid"
]
