## Drivers for InitFS ##

# ahcid
[[drivers]]
name = "AHCI storage"
class = 1
subclass = 6
command = ["ahcid", "$NAME", "$BAR5", "$BARSIZE5", "$IRQ"]

# nvmed
[[drivers]]
name = "NVME storage"
class = 1
subclass = 8
command = ["nvmed"]
use_channel = true

# Disabled until issues are fixed
# # xhcid
# [[drivers]]
# name = "XHCI"
# class = 12
# subclass = 3
# interface = 48
# command = ["xhcid"]
# use_channel = true
