[package]
name = "pcspkrd"
version = "0.1.0"
authors = ["Tibor Nagy <xnagytibor@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../../common" }
redox_syscall = "0.5"
redox-daemon = "0.1"
libredox = "0.1.3"
