[package]
name = "rtl8168d"
version = "0.1.0"

[dependencies]
bitflags = "0.7"
netutils = { git = "https://gitlab.redox-os.org/redox-os/netutils.git", branch = "redox-unix" }
redox_event = { git = "https://gitlab.redox-os.org/redox-os/event.git" }
redox_syscall = "0.1"
