[package]
name = "vesad"
version = "0.1.0"

[dependencies]
hound = "3.3"
lazy_static = "1.0"
orbclient = "0.3"
ransid = "0.4"
rusttype = { version = "0.2", optional = true }
redox_syscall = "0.1"

[features]
default = ["rusttype"]
