[package]
name = "ihdad"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1"
spin = "0.9"
redox_event = { git = "https://gitlab.redox-os.org/redox-os/event.git" }
redox_syscall = "0.2.9"
