[package]
name = "ahcid"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1.2"
byteorder = "1.2"
partitionlib = { git = "https://gitlab.redox-os.org/redox-os/partitionlib.git" }
redox_syscall = "0.1"
