[package]
name = "xhcid"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "0.7"
plain = "0.2"
spin = "0.4"
redox_event = { git = "https://gitlab.redox-os.org/redox-os/event.git" }
redox_syscall = "0.1"
