[package]
name = "ps2d"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "0.7"
orbclient = "0.3.27"
redox_event = { git = "https://gitlab.redox-os.org/redox-os/event.git" }
redox_syscall = "0.1"
