[package]
name = "acpid"
version = "0.1.0"
authors = ["4lDO2 <4lDO2@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
parking_lot = "0.11.1"
plain = "0.2.3"
redox_syscall = "0.2.5"
thiserror = "1"
